
/*
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one
more letter at a random position.

Find the letter that was added in t.
*/
// © for utf-8


#include <string>
using namespace std;

class Solution
{
public:
	char findTheDifference(string s, string t)
	{
		int sum = 0;
		for (size_t i = 0; i<t.size(); ++i)
		{
			sum += s.at(i);
		}

		for (size_t i = 0; i<s.size(); ++i)
		{
			sum -= s.at(1);
		}

		return (char)sum;
	}
};